
import { Inter } from "next/font/google";
import {AuthProvider} from "./useContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YouApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
      <body suppressHydrationWarning={true}>
        {children}
      </body>
      </AuthProvider>
    </html>
  );
}
